Repository srid/neuron, pull requests merged in 2020-04, with the labels that each got.

#63 Add math support documentation in guide
  guide/2011404.md
  guide/2013701.md
Labels: documentation

#92 Add support for custom alias redirects
  CHANGELOG.md
  guide/2011701.md
  neuron.cabal
  src-bin/Main.hs
  src-dhall/Config/Default.dhall
  src-dhall/Config/Type.dhall
  src/Neuron/Parser.hs
  src/Neuron/Zettelkasten.hs
  src/Neuron/Zettelkasten/Config.hs
  src/Neuron/Zettelkasten/ID.hs
  src/Neuron/Zettelkasten/Route.hs
  src/Neuron/Zettelkasten/View.hs
  test/Neuron/Zettelkasten/ConfigSpec.hs
Labels: enhancement

#90 Web search
  src-js/search.js
  src/Neuron/Zettelkasten.hs
  src/Neuron/Zettelkasten/Link/Action.hs
  src/Neuron/Zettelkasten/Link/View.hs
  src/Neuron/Zettelkasten/Query.hs
  src/Neuron/Zettelkasten/Route.hs
  src/Neuron/Zettelkasten/View.hs
Labels: enhancement

#102 ZettelStore: more helpful lookup failure message
  src/Neuron/Zettelkasten/Store.hs
  test/Neuron/Zettelkasten/StoreSpec.hs
Labels: regression

#133 guide: Images should be put into the 'static' folder
  guide/2011404.md
  guide/2016401.md
Labels: documentation
